"""update

Revision ID: 6b3a74686a86
Revises: 2b6c1adfb750
Create Date: 2023-06-08 13:53:47.806953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3a74686a86'
down_revision = '2b6c1adfb750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
